version: '1'
services:
  server:
    container_name: server-prod
    image: milz6525/note-d-server:latest
    restart: "always"
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.production
  client:
    container_name: client-prod
    image: milz6525/note-d-client:latest
    restart: "always"
    ports:
      - 3000:80
    environment:
      - NODE_ENV=production
    depends_on:
      - server 