version: '1'
services:
  backend:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env.development
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
