version: '0.1.0'
services:
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env.development
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - server
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    tty: true
