version: '1'
services:
  client:
    container_name: production-client
    build: 
      context: ./client
      dockerfile: Dockerfile.stage
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production